import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validateCatalog } from '../scripts/content-rules.mjs';
const catalog=JSON.parse(await readFile(new URL('../content/catalog.json',import.meta.url),'utf8')); const lot=JSON.parse(await readFile(new URL('../content/lots/lot-0051.json',import.meta.url),'utf8')); const taxonomy=JSON.parse(await readFile(new URL('../content/lots/lot-0051-taxonomy.json',import.meta.url),'utf8')); const applicability=JSON.parse(await readFile(new URL('../content/content-applicability.json',import.meta.url),'utf8')); const find=(collection,id)=>collection.find((item)=>item.id===id); const ids=['Q000434','Q000435','Q000436','Q000437','Q000438','Q000439','Q000440']; const answers=['C','B','A','D','C','E','D'];
test('LOT-0051 permanece íntegro no catálogo v61 sem reduzir validações',()=>{assert.deepEqual(validateCatalog(catalog),[]); assert.equal(lot.lotId,'LOT-0051'); assert.equal(lot.contentVersion,50); assert.equal(catalog.contentVersion,61); assert.equal(catalog.publication.lotId,'LOT-0062'); assert.equal(catalog.units.length,61); assert.equal(catalog.materials.length,61); assert.equal(catalog.questions.length,420); assert.equal(catalog.questionSets.length,61);});
test('U050 preserva fontes e separação teoria/questões',()=>{const unit=find(catalog.units,'U050'); assert.ok(unit); assert.deepEqual(unit.coverage,['PMDF','PMGO']); assert.deepEqual(unit.materialIds,['M050']); assert.deepEqual(unit.questionIds,ids); assert.deepEqual(unit.questionSetIds,['QS050']); assert.deepEqual(unit.sourceIds,['FNT-0004']); const material=find(catalog.materials,'M050'); assert.ok(material); assert.equal(material.unitId,'U050'); assert.equal(material.type,'Aula teórica'); assert.equal('questionIds' in material,false); assert.equal('answer' in material,false); assert.equal('options' in material,false); ids.forEach((id,index)=>{const q=find(catalog.questions,id); assert.ok(q,id); assert.equal(q.unitId,'U050',id); assert.equal(q.answer,answers[index],id); assert.equal(q.options.length,5,id); assert.ok(q.options.some((o)=>o.id===answers[index]),id); assert.deepEqual(q.sourceIds,['FNT-0004'],id); assert.ok(q.commentary.length>20,id); assert.ok(q.foundation.length>10,id); assert.equal(q.annulled,false,id); assert.equal(q.duplicateOf,null,id); assert.equal(q.imageRequired,false,id); assert.equal(q.valid,true,id);}); const set=find(catalog.questionSets,'QS050'); assert.ok(set); assert.equal(set.unitId,'U050'); assert.deepEqual(set.questionIds,ids); assert.equal(set.correctionMode,'Ao finalizar'); assert.equal('questions' in set,false); assert.equal('answers' in set,false);});
test('taxonomia do crime militar preserva relação pai-filho',()=>{const parent=find(taxonomy.topics,'ASS-DPM-002'); const child=find(taxonomy.topics,'ASS-DPM-002-01'); assert.ok(parent); assert.ok(child); assert.equal(parent.subjectId,'MAT-DPM'); assert.equal(child.subjectId,'MAT-DPM'); assert.equal(child.parentId,'ASS-DPM-002');});
test('U050 tem aplicabilidade explícita PMDF + PMGO sem ativar rotação específica',()=>{const rule=applicability.unitApplicability.find((item)=>item.unitId==='U050'); assert.ok(rule); assert.equal(rule.classification,'shared-2'); assert.deepEqual(rule.competitions,['PMDF','PMGO']); assert.deepEqual(rule.evidenceIds,['FNT-0015','FNT-0014','FNT-0004']); assert.equal(applicability.specificRotation.enabled,false);});
