import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validateCatalog } from '../scripts/content-rules.mjs';
const catalog = JSON.parse(await readFile(new URL('../content/catalog.json', import.meta.url), 'utf8'));
function findById(collection, id) { return collection.find((item) => item.id === id); }
test('LOT-0008 permanece íntegro no catálogo cumulativo posterior', () => { assert.deepEqual(validateCatalog(catalog), []); assert.ok(catalog.contentVersion >= 8); assert.ok(findById(catalog.units,'U008')); assert.ok(findById(catalog.materials,'M008')); assert.ok(findById(catalog.questionSets,'QS008')); });
test('U008 referencia taxonomia, fonte e componentes auditados', () => { const unit=findById(catalog.units,'U008'); assert.ok(unit); assert.equal(unit.subjectId,'MAT-DCON'); assert.deepEqual(unit.topicIds,['ASS-DCON-002']); assert.deepEqual(unit.sourceIds,['FNT-0001']); assert.deepEqual(unit.materialIds,['M008']); assert.deepEqual(unit.questionIds,['Q000043','Q000044','Q000045','Q000046','Q000047','Q000048','Q000049']); assert.deepEqual(unit.questionSetIds,['QS008']); });
test('M008 mantém teoria separada das questões e orientação de revisão', () => { const material=findById(catalog.materials,'M008'); assert.ok(material); assert.equal(material.unitId,'U008'); assert.equal(material.required,true); assert.equal('questionIds' in material,false); assert.equal('answer' in material,false); assert.equal('options' in material,false); const headings=material.blocks.filter(({type})=>type==='heading').map(({text})=>text); for(const term of ['Erros comuns','Resumo da aula','Orientação de revisão']) assert.ok(headings.some((heading)=>heading.includes(term))); });
test('sete questões da U008 mantêm gabaritos e integridade editorial', () => { const expected={Q000043:'C',Q000044:'B',Q000045:'C',Q000046:'D',Q000047:'A',Q000048:'D',Q000049:'A'}; for(const [id,answer] of Object.entries(expected)){const question=findById(catalog.questions,id); assert.ok(question,id); assert.equal(question.answer,answer,id); assert.equal(question.unitId,'U008',id); assert.equal(question.subjectId,'MAT-DCON',id); assert.deepEqual(question.sourceIds,['FNT-0001'],id); assert.equal(question.options.length,5,id); assert.ok(question.options.some((option)=>option.id===answer),id); assert.ok(question.commentary.length>20,id); assert.ok(question.foundation.length>10,id); assert.equal(question.annulled,false,id); assert.equal(question.duplicateOf,null,id); assert.equal(question.imageRequired,false,id); assert.equal(question.valid,true,id); }});
test('QS008 apenas referencia questões do Banco Mestre na ordem auditada', () => { const set=findById(catalog.questionSets,'QS008'); assert.ok(set); assert.equal(set.unitId,'U008'); assert.equal(set.correctionMode,'Por questão'); assert.deepEqual(set.questionIds,['Q000043','Q000044','Q000045','Q000046','Q000047','Q000048','Q000049']); assert.equal('questions' in set,false); assert.equal('answers' in set,false); });
test('FNT-0001 permanece fonte normativa primária e vigente', () => { const source=findById(catalog.sources,'FNT-0001'); assert.ok(source); assert.equal(source.official,true); assert.equal(source.priority,'Primária'); assert.equal(source.temporalStatus,'Vigente'); });
